### ISSUE TITLE
Please design a Logo

### ISSUE THREAD

**Issue by yorkbeary** [billlipeng/ECEN689-602-Spring2015#6]
We have color display, so we'd better have a Logo icon, something meaningful for our team.

**Comment by baiyz** [comment]
![image](https://cloud.githubusercontent.com/assets/8716986/6613022/7e38231e-c854-11e4-8700-7aaf17d7d7fd.jpg)

**Comment by baiyz** [comment]
Skelecton is our Ballbot base, which is a triangular hexagon, like a shield
Center is a yellow circle which is tangent to three color wings, red-green-blue
Name of the team: Tedron (Tetrahedron)

**Comment by yorkbeary** [comment]
I think we should have less colors. You are using nearly all basic colors.  Too vibrant. zi suggest a theme color. What do u think

**Comment by baiyz** [comment]
暂定铜黑色色调，代表电子电力电气，稳重大气，像这个一样

**Comment by billlipeng** [comment]
Guys, I created a Private repository on Github. Please confirm invitation email.

**Comment by baiyz** [comment]
Please change the name of ECEN689-602-Spring2015 to a more meaningful name:
like Ballbot

Thanks,
Zoy

On Thu, Mar 12, 2015 at 4:34 PM, Peng Li <notifications@github.com> wrote:

> Guys, I created a Private repository on Github. Please confirm invitation
> email.
>
>
> > On Mar 12, 2015, at 4:03 PM, Yangzheng Zoy BAI <notifications@github.com>
> wrote:
> >
> > 暂定铜黑色色调，代表电子电力电气，稳重大气，像这个一样
> >
> >
> >
> >
> > Sent from my iPhone
> >
> > On Mar 12, 2015, at 3:44 AM, Zijiang Yang <notifications@github.com>
> wrote:
> >
> > > I think we should have less colors. You are using nearly all basic
> colors. Too vibrant. zi suggest a theme color. What do u think
> > >
> > > Sent from my iPad
> > >
> > > > On 12 Mar, 2015, at 2:28 pm, Yangzheng Zoy BAI <
> notifications@github.com> wrote:
> > > >
> > > > Skelecton is our Ballbot base, which is a triangular hexagon, like a
> shield
> > > > Center is a yellow circle which is tangent to three color wings,
> red-green-blue
> > > > Name of the team: Tedron (Tetrahedron)
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/billlipeng/ECEN689-602-Spring2015/issues/6#issuecomment-78616269
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/billlipeng/ECEN689-602-Spring2015/issues/6#issuecomment-78629697>
> .
>



-- 
Supported by Yangzheng BAI (Zoy)
2002-2013

**Comment by baiyz** [comment]
This name is exactly the same as previous public repository, please change
it to Ballbot or Tedron, which easily distinguished as private repository

On Thu, Mar 12, 2015 at 4:49 PM, Yangzheng Zoy BAI <bairyz@gmail.com> wrote:

> Please change the name of ECEN689-602-Spring2015 to a more meaningful
> name: like Ballbot
>
> Thanks,
> Zoy
>
> On Thu, Mar 12, 2015 at 4:34 PM, Peng Li <notifications@github.com> wrote:
>
>> Guys, I created a Private repository on Github. Please confirm invitation
>> email.
>>
>>
>> > On Mar 12, 2015, at 4:03 PM, Yangzheng Zoy BAI <
>> notifications@github.com> wrote:
>> >
>> > 暂定铜黑色色调，代表电子电力电气，稳重大气，像这个一样
>> >
>> >
>> >
>> >
>> > Sent from my iPhone
>> >
>> > On Mar 12, 2015, at 3:44 AM, Zijiang Yang <notifications@github.com>
>> wrote:
>> >
>> > > I think we should have less colors. You are using nearly all basic
>> colors. Too vibrant. zi suggest a theme color. What do u think
>> > >
>> > > Sent from my iPad
>> > >
>> > > > On 12 Mar, 2015, at 2:28 pm, Yangzheng Zoy BAI <
>> notifications@github.com> wrote:
>> > > >
>> > > > Skelecton is our Ballbot base, which is a triangular hexagon, like
>> a shield
>> > > > Center is a yellow circle which is tangent to three color wings,
>> red-green-blue
>> > > > Name of the team: Tedron (Tetrahedron)
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub.
>> > > >
>> > > —
>> > > Reply to this email directly or view it on GitHub.
>> > >
>> > —
>> > Reply to this email directly or view it on GitHub <
>> https://github.com/billlipeng/ECEN689-602-Spring2015/issues/6#issuecomment-78616269
>> >.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/billlipeng/ECEN689-602-Spring2015/issues/6#issuecomment-78629697>
>> .
>>
>
>
>
> --
> Supported by Yangzheng BAI (Zoy)
> 2002-2013
>



-- 
Supported by Yangzheng BAI (Zoy)
2002-2013

**Comment by billlipeng** [comment]
I can’t change it once it was created. Please create a new one if you like change the name.

**Comment by billlipeng** [comment]
Or, you can move all the staff here to that one. I have moved most of it.

**Comment by yorkbeary** [comment]
I think the name is irrelevant, as long as it's private. Now I can upload the full source code Thank you Billy the Penguin!

**Comment by baiyz** [comment]
Okay, then we switch to this private git, thank you, Billy
